name: MojCimer watcher (Telegram)

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Restore last seen.json (gets the most recent cache with prefix "seen-")
      - name: Restore seen.json cache
        uses: actions/cache/restore@v4
        with:
          path: seen.json
          key: seen-${{ github.run_id }}
          restore-keys: |
            seen-

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install -r requirements.txt

      - name: Run watcher
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python mojcimer_watcher.py

      # Save updated seen.json so the next run remembers it
      - name: Save seen.json cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: seen.json
          key: seen-${{ github.run_id }}
